services:
  - type: web
    name: pharmaguard
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: NODE_VERSION
        value: "20"
      - key: GOOGLE_API_KEY
        sync: false
